### ISSUE TITLE
Highlight errors inside #if 0

### ISSUE THREAD

**Issue by hungnguyen1503** [HiPhish/nvim-ts-rainbow2#17]
**Describe the bug**

If brackets are inside 0 then the rainbow will highlight it.

**Expected behavior**

Could you please support me with a config rainbow plugin?

**Screenshots**

![image](https://user-images.githubusercontent.com/58872428/225852460-b8e64d1b-2257-4e80-aa6d-c7308abea375.png)

**Comment by HiPhish** [comment]
I don't understand the question. Are you saying that you want the braces to be highlighted when the cursor is on top of the zero, or do you not want the braces to be highlighted?

**Comment by hungnguyen1503** [comment]
Yes, That's what I want.

**Comment by HiPhish** [comment]
Which of the two?

**Comment by hungnguyen1503** [comment]
I don't want the braces to be highlighted in `#if 0` because `#if 0` is equivalent to comment code in C language

**Comment by HiPhish** [comment]
Your code won't work because it is invalid C. You need a name for the new type
after the structure declaration:

```c
typedef struct {
    struct_b b;
} my_struct_t;
```

But even with that out of the way, I don't know how to make it work. Here is a query which matches your requirements:

```
(preproc_if
  condition: (number_literal) @cond (#not-eq? @cond "0")
  (type_definition
    (struct_specifier
      (field_declaration_list
        "{" @opening
        "}" @closing) @container)))
```

The key is the predicate check `(#not-eq? @cond "0")` which makes sure that the
number (which must be a literal) is not zero. However, you will still get
highlighting because this other query still matches:

```
(field_declaration_list
   (("{" @opening)
    ("}" @closing))) @container
```

You could try to remove that query, but then highlighting of structure brackets
won't work anywhere but an `#if` context. The only solution I could imagine is
to write a custom predicate (see `:h treesitter-predicates`) which checks that the
syntax highlight group of the `@container` capture to see if it is the comment
group.

**Comment by hungnguyen1503** [comment]
Hi, I checked the issues of my source code, and it seems that the error is from clangd, I tried config Clangd on Visual Studio Code and it gives me the same error. Your plugin works great.
Thank you for your support, this ticket can be closed.
