### ISSUE TITLE
Cannot highlight parentheses in real-time

### ISSUE THREAD

**Issue by lzlcs** [HiPhish/nvim-ts-rainbow2#52]
I have to restart nvim so that the paraentheses can be highlighted

**Comment by HiPhish** [comment]
What language? Which strategy?

**Comment by lzlcs** [comment]
Language `scheme`
Strategy: I have tried both global and local strategies

https://github.com/HiPhish/nvim-ts-rainbow2/assets/61308957/9abd755e-e7e3-437c-9804-5547b23513f3

**Comment by lzlcs** [comment]
I apologize for not providing detailed information

Ubuntu 22.04LTS (WSL2)
Language: `scheme`
Strategy: I have tried both global and local strategies
Plugins Manageer: Lazy

My config:
```lua
rainbow = {
  enable = true,
  -- Which query to use for finding delimiters
  query = 'rainbow-parens',
  -- Highlight the entire buffer all at once
  strategy = require('ts-rainbow').strategy.global,
}
```


https://github.com/HiPhish/nvim-ts-rainbow2/assets/61308957/9bc2ed4e-1b62-4cd2-841e-4fd23421185d

**Comment by HiPhish** [comment]
That is very strange, it works perfectly for me with Scheme. What is your
output of `:set filetype?`? Tree-sitter queries also use the file extension
`scm` and Neovim might be setting the file type incorrectly. I doubt that's the
problem, but we need to be certain.

Does the highlighting get applied when you execute `:edit` on your buffer? What
happens if you add parentheses to an already highlighted section?

**Comment by lzlcs** [comment]
```
:set filetype
```
Output:
```
filetype=scheme
```


https://github.com/HiPhish/nvim-ts-rainbow2/assets/61308957/6b1bce6d-718c-4a1e-b3fe-8c79103959a2

**Comment by HiPhish** [comment]
OK, now I'm really out of ideas. Can you please try a minimal setup with only nvim-treesitter and nvim-ts-rainbow2 as the only plugins? See `:h $NVIM_APPNAME` for how to set up a configuration under a different name.

**Comment by lzlcs** [comment]
Crazy

https://github.com/HiPhish/nvim-ts-rainbow2/assets/61308957/3f7a6667-46ac-42e1-a2e2-0c9d4cf21179

**Comment by HiPhish** [comment]
I probably won't fix this in this repo. The nvim-treesitter plugin has deprecated the module system, so I am working on a standalone version of this plugin. It's mostly done, but since configuration is different I will make it a new plugin. The code is more or less the same and I have been able to solve some other issues along the way simply by not using the nvim-treesitter module system. I don't know if this issue will also get fixed "for free", but I don't really want to invest more time into a dying plugin.

The transition will be easy, most of the configuration can stay the same. The main difference is where and how it is applied. I will post in this thread once the new plugin is up.

**Comment by lzlcs** [comment]
Thank you.

**Comment by HiPhish** [comment]
The new rainbow plugin is here: [rainbow-delimiters.nvim](https://gitlab.com/HiPhish/rainbow-delimiters.nvim) ([GitHub mirror](https://gitlab.com/HiPhish/rainbow-delimiters.nvim)). Please file an issue over there if the problem still persists.
