### ISSUE TITLE
Feature request: custom colors

### ISSUE THREAD

**Issue by amaanq** [HiPhish/nvim-ts-rainbow2#6]
I could be mistaken and missed the option for this somewhere, but with the old ts-rainbow plugin I had my colors defined as a colors key like so:
```lua
colors = {
	"royalblue3",
	"darkorange3",
	"seagreen3",
	"firebrick",
	"darkorchid3",
},
```

This was convenient as I liked these colors, only wanted 5 (not all 7 of the rainbow colors), and was easy to add.

It'd be nice to see similar functionality added here if it doesn't already exist (again I might've completely missed it)

Thanks!

**Comment by HiPhish** [comment]
Hi,

see `:h ts-rainbow-colors` in the manual for how to specify colours; this fork uses highlight groups instead of hex colour codes. Why highlight groups? Because that is the Vim way.

- Highlight groups are used throughout the Vim and Neovim functions
- We can support both true colour (GUI) and colour terminals
- We can link to existing highlight groups from colour schemes
- We get support for switching colour schemes on the fly for free.
- We can make use of all the highlight group properties, such as underlining or italics

Even the original plugin was using highlight groups internally. Here is an example of how you can get what you want:

```lua
-- First we have to redefine the highlight groups
vim.api.nvim_set_hl(0, 'TSRainbowRed',    {fg = 'royalblue3'})
vim.api.nvim_set_hl(0, 'TSRainbowYellow', {fg = 'darkorange3'})
vim.api.nvim_set_hl(0, 'TSRainbowBlue',   {fg = 'seagreen3'})
vim.api.nvim_set_hl(0, 'TSRainbowOrange', {fg = 'firebrick'})
vim.api.nvim_set_hl(0, 'TSRainbowGreen',  {fg = 'darkorchid3'})

-- Now we specify those five groups in the rainbow settings
require('nvim-treesitter.configs').setup {
    rainbow = {
        hlgroups = {
            `TSRainbowRed`,
            `TSRainbowYellow`,
            `TSRainbowBlue`,
            `TSRainbowOrange`,
            `TSRainbowGreen`,
        }
    }
}
```

You don't have to use the `TSRainbow...` groups, you can used whatever highlight groups you want if you already have some that you want to reuse.

If this answers your question please close the issue.

**Comment by amaanq** [comment]
Thanks! That is indeed better functionality, especially since it follows Vim convention. Closing.
